//user
export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE'
export const USER_REGISTER = 'USER_REGISTER'
export const USER_REGISTER_FAILURE = 'USER_REGISTER_FAILURE'
export const USER_LOGOUT = 'USER_LOGOUT'

//article
export const ARTICLE_GET = "ARTICLE_GET"
export const ARTICLE_GET_FAILURE = "ARTICLE_GET_FAILURE"
export const ARTICLE_POST = "ARTICLE_POST"

//articleDetails
export const ARTICLE_LOADING = "ARTICLE_LOADING"


